import { a9 as head } from "../../../../chunks/index2.js";
function _page($$renderer) {
  head("1mofc72", $$renderer, ($$renderer2) => {
    $$renderer2.title(($$renderer3) => {
      $$renderer3.push(`<title>Contact</title>`);
    });
  });
  $$renderer.push(`<div class="max-w-2xl"><h1>Let's Work Together</h1> <p class="mb-4 text-lg">We help organizations transform data into competitive advantage. Whether you're exploring your first data solution or optimizing your current systems, we're here to help.</p> <p class="mb-8">Fill out the form below and tell us about your challenge. We'll review your request and follow up within one business day with next steps.</p> <div class="mb-12 p-6 bg-base-200 rounded-lg"><h3 class="text-lg font-semibold mb-3">To help us serve you better, please share:</h3> <ul class="list-disc list-inside space-y-2"><li><strong>Your Challenge</strong> — What's the business problem you're trying to solve?</li> <li><strong>Current State</strong> — What systems or processes do you have today?</li> <li><strong>Desired Outcome</strong> — What would success look like for your team?</li> <li><strong>Timeline</strong> — When are you looking to get started?</li></ul></div> <form netlify="" id="contactForm" class="grid grid-flow-row gap-6" name="contact" method="POST" data-netlify="true" data-netlify-recaptcha="true" netlify-honeypot="bot-field"><div><label for="name" class="block font-semibold mb-2">Your Name</label> <input id="name" placeholder="John Smith" type="text" name="name" class="input input-bordered w-full max-w-sm text-white" required=""/></div> <div><label for="business" class="block font-semibold mb-2">Company / Organization</label> <input id="business" placeholder="Company Name" type="text" name="business" class="input input-bordered w-full max-w-sm text-white" required=""/></div> <div><label for="email" class="block font-semibold mb-2">Email Address</label> <input id="email" placeholder="you@company.com" type="email" name="email" class="input input-bordered w-full max-w-sm text-white" required=""/></div> <div><label for="phone" class="block font-semibold mb-2">Phone Number</label> <input id="phone" placeholder="(555) 123-4567" type="tel" name="phone" class="input input-bordered w-full max-w-sm text-white"/></div> <div><label for="message_body" class="block font-semibold mb-2">Tell Us About Your Challenge</label> <textarea id="message_body" name="message_body" class="textarea textarea-bordered w-full max-w-xl text-white" placeholder="Describe your situation, goals, and any relevant context. The more detail you provide, the better we can prepare for our conversation." rows="6" required=""></textarea></div> <input type="hidden" name="form-name" value="contact"/> <div class="pt-2"><button class="btn btn-primary btn-lg" type="submit">Send Message</button></div></form> <div class="mt-12 pt-8 border-t border-base-300"><h3 class="font-semibold mb-2">What Happens Next?</h3> <ol class="list-decimal list-inside space-y-2"><li>We review your message and understand your challenge</li> <li>We'll reach out within 24 hours to discuss your situation</li> <li>If it's a good fit, we'll propose next steps and pricing</li></ol></div></div>`);
}
export {
  _page as default
};
