import { ab as head } from "../../../../chunks/index2.js";
function _page_md($$renderer) {
  head("1z5oxm", $$renderer, ($$renderer2) => {
    $$renderer2.title(($$renderer3) => {
      $$renderer3.push(`<title>Services</title>`);
    });
  });
  $$renderer.push(`<h1 id="services"><a aria-hidden="true" tabindex="-1" href="#services"><span class="icon icon-link"></span></a>Services</h1> <p>Technology solutions are widely varying in complexity and scope. For this reason we set starting costs for services. This is to allow for a successful service, even if the goal is a large one. Generally, services are priced at $200 per hour.</p> <h2 id="consultation"><a aria-hidden="true" tabindex="-1" href="#consultation"><span class="icon icon-link"></span></a>Consultation</h2> <ul><li>Macro Process Diagramming</li></ul> <p>Starting at $200</p> <br/> <ul><li>Solution Design &amp; Statement of Work (SoW)</li></ul> <p>Starting at $800</p> <br/> <ul><li>Software Product Research</li></ul> <p>Starting at $200</p> <br/> <ul><li>Software Request For Proposal (RFP)</li></ul> <p>Starting at $600</p> <br/> <ul><li>Machine Learning / AI Model Bias &amp; Fairness Analysis</li></ul> <p>Starting at $2000</p> <br/> <ul><li>Business Start-Up Technology Strategy</li></ul> <p>$250 per hour</p> <br/> <ul><li>Data &amp; AI Strategy</li></ul> <p>$250 per hour</p> <br/> <h2 id="implementation--administration"><a aria-hidden="true" tabindex="-1" href="#implementation--administration"><span class="icon icon-link"></span></a>Implementation &amp; Administration</h2> <ul><li>Website Design &amp; Development <ul><li>Landing and informational pages</li> <li>Web forms such as contact or online applications</li> <li>Blog posting and Content Management Systems</li> <li>Low hosting fees starting at $0 / month</li></ul></li></ul> <p>Starting at $400</p> <br/> <ul><li><p>Software Onboarding &amp; Configuration</p> <ul><li>VOIP Phone &amp; SMS</li> <li>Office Software &amp; Email</li> <li>Customer Relationship Manager</li> <li>Entity Relationship Manager</li> <li>Other software systems</li></ul></li></ul> <p>Starting at $400</p> <br/> <ul><li>Low Code Automation or Integration</li></ul> <p>Starting at $400</p> <br/> <ul><li>Full Code Automation or Integration</li></ul> <p>Starting at $1000</p> <br/> <ul><li>Software Maintenance and Updates</li></ul> <p>Starting at $200 / month</p> <br/> <h2 id="training--support"><a aria-hidden="true" tabindex="-1" href="#training--support"><span class="icon icon-link"></span></a>Training &amp; Support</h2> <ul><li>Live training</li></ul> <p>$300 per hour</p> <br/> <ul><li>Technical Support</li></ul> <p>$200 per hour</p> <br/>`);
}
export {
  _page_md as default
};
